apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/sowens2nd/awx-operator/config/default?ref=2.19.2
  - awx-nprd.yml
# Set the image tags to match the git version from above
images:
  - name: p004mgmtaksacrea01.azurecr.io/awx-operator
    newTag: 2.19.2

# Specify a custom namespace in which to install AWX
namespace: awx