- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - basic-check-spec
    image: p004mgmtaksacrea01.azurecr.io/scorecard-test:v1.26.0
    labels:
      suite: basic
      test: basic-check-spec-test
